// Generated by https://quicktype.io

import { Store } from "./store.models";

export interface AuthResponse {
  user:  User;
  token: string;
  store: Store;
}


export interface User {
  _id: string;
  name: string;
  email: string;
  role: string;
  dashboard_theme: 'light' | 'dark' | 'dark-blue';
  createdAt: string;
  updatedAt: string;
  __v: number;
  active_store: string;
}
