// Generated by https://quicktype.io


export interface Store {
  setup_guide: SetupGuide;
  remitance_account: RemitanceAccount;
  theme: Theme;
  _id: string;
  owner: string;
  store_name: string;
  slug: string;
  store_email: string;
  store_url: string;
  location: string;
  categories: Category[];
  allow_pay_on_delivery: boolean;
  socials: Social[];
  coupons: Coupon[];
  shipping_options: ShippingOption[];
  banners: Banner[];
  createdAt: string;
  updatedAt: string;
  __v: number;
  description: string;
  tag_line: string;
  category: string;
}

export interface Banner {
  header: string;
  sub_text: string;
  background_image: string;
  _id: string;
}

export interface Coupon {
  code: string;
  discount_type: string;
  show_on_site: boolean;
  value: string;
  _id: string;
  start_date: string;
  end_Date: string;
}

export interface RemitanceAccount {
  bank_name: string;
  account_name: string;
  account_number: string;
}

export interface SetupGuide {
  is_complete: boolean;
  last_step: number;
}

export interface Category {
  name: string;
  media: string
  slug: string
  _id: string
}

export interface ShippingOption {
  name: string;
  price: number;
  _id: string;
}

export interface Social {
  platform: string;
  url: string;
  _id: string;
}

export interface Theme {
  color: Color;
  active_theme: ThemeOptions;
}

export interface Color {
  primary: string;
  secondary: string;
}

export type ThemeOptions =
  | 'minimal'
  | 'trendy'
  | 'classic'
  | 'retro'
  | 'antique';


export const categories = [
  { name: 'Electronics' },
  { name: 'Fashion' },
  { name: 'Home & Kitchen' },
  { name: 'Beauty & Personal Care' },
  { name: 'Books' },
  { name: 'Toys & Games' },
  { name: 'Sports & Outdoors' },
  { name: 'Automotive' },
  { name: 'Health & Wellness' },
  { name: 'Grocery' },
  { name: 'Office Supplies' },
  { name: 'Pet Supplies' },
  { name: 'Jewelry & Watches' },
  { name: 'Music & Instruments' },
  { name: 'Baby Products' },
  { name: 'Tools & Hardware' },
  { name: 'Garden & Outdoor' },
  { name: 'Furniture' },
  { name: 'Art & Craft Supplies' },
  { name: 'Travel & Luggage' },
];
