// Generated by https://quicktype.io

export interface AuthResponse {
  user:  User;
  token: string;
  store: Store;
}

export interface Store {
  setup_guide:           SetupGuide;
  theme:                 Theme;
  _id:                   string;
  owner:                 string;
  store_name:            string;
  slug:                  string;
  store_email:           string;
  store_url:             string;
  location:              string;
  categories:            any[];
  allow_pay_on_delivery: boolean;
  socials:               any[];
  coupons:               any[];
  shipping_options:      any[];
  banners:               any[];
  createdAt:             string;
  updatedAt:             string;
  __v:                   number;
}

export interface SetupGuide {
  is_complete: boolean;
  last_step:   number;
}

export interface Theme {
  color:        Color;
  active_theme: string;
}

export interface Color {
  primary:   string;
  secondary: string;
}

export interface User {
  _id:             string;
  name:            string;
  email:           string;
  role:            string;
  dashboard_theme: string;
  createdAt:       string;
  updatedAt:       string;
  __v:             number;
  active_store:    string;
}
